### ISSUE TITLE
μBlock icon inside Firefox's menu doesn't show its content properly

### ISSUE THREAD

**Issue by crisalis** [uBlock-LLC/uBlock#1015] opened 2015-03-15 09:41 UTC
When you place the μBlock icon inside Firefox's menu and tell it to show the details about blocked requests, the width of the content μBlock shows is larger than its container's width, and thus you can't see said content properly. No horizontal scrollbar appears and scrolling with mouse wheel or touchpad doesn't work; the only way to scroll through the content is to press right and left arrow keys.

![kdfnbkdfn](https://cloud.githubusercontent.com/assets/10261623/6655390/3c827084-caff-11e4-8763-49e753fd8e46.gif)

This might be a Firefox problem, not μBlock's.

**Comment by gorhill** [comment] 2015-03-15 11:15
Duplicate of #505.

**Closed as completed by gorhill** 2015-03-15 11:15 UTC

**Comment by crisalis** [comment] 2015-03-15 14:29
Welp, sorry.
