### ISSUE TITLE
support the ABP links

### ISSUE THREAD

**Issue by ivysrono** [uBlock-LLC/uBlock#813] opened 2015-02-16 14:08 UTC
Known Adblock Plus subscriptions
https://adblockplus.org/en/subscriptions

abp:subscribe?location=https%3A%2F%2Feasylist-downloads.adblockplus.org%2Feasylist.txt&title=EasyList

Click then add to custom list

**Comment by gorhill** [comment] 2015-02-16 14:09
Duplicate of #224.

**Closed as completed by gorhill** 2015-02-16 14:09 UTC
