### ISSUE TITLE
[Safari] ublock resets/reinstall when safari history deleted

### ISSUE THREAD

**Issue by Mojmir50** [uBlock-LLC/uBlock#1091] opened 2015-03-25 15:52 UTC
hello, ublock is great, but suffers bug that had adblock plus in past. When I delete safari history (clear history and website data) it also deletes all ublock settings (it looks like freshly installed)

here is article how its solved in adblock plus /its exactly same bug/

https://adblockplus.org/development-builds/fixing-data-corruptions-in-adblock-plus-for-safari

could you please fix that? thank you :)

**Comment by gorhill** [comment] 2015-03-25 16:04
Duplicate of #1055.

**Closed as completed by gorhill** 2015-03-25 16:04 UTC
