### ISSUE TITLE
[Firefox 36] Unable to access the settings via menu button ≡

### ISSUE THREAD

**Issue by andrey-budko** [uBlock-LLC/uBlock#876] opened 2015-02-24 16:10 UTC
Can't access to FF settings via menu button (three horizontal lines at upper-right corner) if uBlock is enabled and its button is there.
https://dl.dropboxusercontent.com/u/235592644/clip/2015-02-24_17.40.16.png

Menu opens and immediately hides. Sometimes it opens in this way:
https://dl.dropboxusercontent.com/u/235592644/clip/2015-02-24_17.38.16.png

It hides only if uBlock blocked something on active tab (and small red number appears at corner of the icon). So it's still possible to access settings from about:blank, about:addons, etc

Worked fine with FF35.

FF 36, uBlock 0.8.8.2

**Comment by Deathamns** [comment] 2015-02-24 16:25
Duplicate of #638.
Workaround: disable "Show the number of blocked requests on the icon" in the settings.

**Closed as completed by Deathamns** 2015-02-24 16:25 UTC
