### ISSUE TITLE
[Linux Mint/Firefox] Popup symbols disappear when ...

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#814] opened 2015-02-16 14:29 UTC
The symbols in the popup for the power button, eye dropper, and eye disappear when I untick "Allow pages to choose their own fonts, instead of my selections above" in Preferences/Content/Advanced.
This has been happening on both my computers.

**Comment by gorhill** [comment] 2015-02-16 14:35
Duplicate of #629.

**Closed as completed by gorhill** 2015-02-16 14:35 UTC
