### ISSUE TITLE
Links you provided still have old versions

### ISSUE THREAD

**Issue by mikhaelkh** [uBlock-LLC/uBlock#1167] opened 2015-04-02 15:44 UTC
They have 0.9.2.3 instead of 0.9.3.0. It should be nice to synchronize releases here and at the stores.

**Comment by chrisaljoudi** [comment] 2015-04-02 15:48
Hi @mikhaelkh!

I don't have control over the already-existent entries for uBlock on the Chrome Web Store and Opera store (it is currently under @gorhill's control, I believe, and I recall he wishes to keep it that way).

As such, a new [Chrome Web Store entry has been created](https://chrome.google.com/webstore/detail/ublock/epcnnfbjfcgphgdmggkamkmgojdagdnn) — and that one should be up-to-date with 0.9.3.0.

The problem is that the old version is the one that shows up in searches/etc. (the Chrome Web Store already knows about tons of users for that one).

The only way around this without transferring ownership of the Web Store extension would be for @gorhill to perhaps change the name, so people searching for "uBlock" will get the public, latest version.

**Comment by mikhaelkh** [comment] 2015-04-02 15:51
Ok, update the wiki then.

**Comment by chrisaljoudi** [comment] 2015-04-02 15:52
@mikhaelkh oops, sorry I missed that. Changed the link I spotted — anything else I missed?

**Comment by mikhaelkh** [comment] 2015-04-02 15:59
Opera Store still 0.9.2.3, The Safari Extension you've requested is not currently available.
And Firefix Store still 0.8.8.2 & 0.9.1.0 so its best for now to update behind Firefox Store.

**Comment by mikhaelkh** [comment] 2015-04-02 16:05
You perhaps want to work on your [site](https://chrismatic.io/ublock/)

**Comment by chrisaljoudi** [comment] 2015-04-02 16:07
@mikhaelkh as far as I can tell by testing the links on the site, those all give the up-to-date versions. Mind elaborating?

**Comment by mikhaelkh** [comment] 2015-04-02 16:09
Safari: https://chrismatic.io/ublock/ublock-latest.safariextz?0.9.2.3
Firefox: https://github.com/chrisaljoudi/uBlock#firefox
Opera is missing

**Comment by chrisaljoudi** [comment] 2015-04-02 16:24
@mikhaelkh okay, should be "better".

As far as Firefox goes, a reorganization of the way releases work is needed — we're working on figuring out the right answer right now in #1166.

To put it more generally, I'm going to be working to try and get release distribution/versioning as automated as possible, which will make everyone happier.

Opera: honestly, I don't know right now. I'll have to get back to Opera to figure out the right answer. Sorry.

**Comment by mikhaelkh** [comment] 2015-04-02 16:27
You mean #1166

**Comment by rodalpho** [comment] 2015-04-02 18:18
Links inside the addon (in settings, about) also point to the old repository.

**Closed as completed** 2015-04-08 22:41 UTC
