### ISSUE TITLE
data:uri refresh test is failing

### ISSUE THREAD

**Issue by JulianNorton** [uBlock-LLC/uBlock#852] opened 2015-02-20 18:17 UTC
http://raymondhill.net/ublock/popup.html

`data:uri refresh should close automatically`

It's not closing.

**Comment by JulianNorton** [comment] 2015-02-20 18:18
`Version 40.0.2214.115 (64-bit)`

Other tests are also failing

http://cl.ly/2d2x0b261v03

**Comment by gorhill** [comment] 2015-02-20 18:30
Duplicate of #510.

**Closed as completed by gorhill** 2015-02-20 18:30 UTC
