### ISSUE TITLE
[Safari] Updating or applying changes for 3rd party filters loads indefinitely

### ISSUE THREAD

**Issue by Jekecy** [uBlock-LLC/uBlock#914] opened 2015-03-02 00:09 UTC
This has just recently started happening on my Safari extension (Chrome on the same machine works fine).

Whenever I try to apply an update or change, the page "whites out" as normal...but stays like that forever. I can switch panes and still go about my business browsing, but the 3rd party pane is forever in that loading state until I close preferences and open it up again.

**Comment by chrisaljoudi** [comment] 2015-03-02 00:54
@Jekecy sorry to hear about that.

What filter lists do you have enabled? Also, what version of µBlock is this occurring on?

**Comment by Jekecy** [comment] 2015-03-02 01:00
Hm, strangely it seems to be working now. I just uninstalled and reinstalled again, but this time I hit the 'Update Now' button first instead of 'Apply Changes' on the 3rd party pane. Now everything is working as it should. I don't want to mess around with it anymore in fear of breaking something again, so I guess you can just cross this issue off for now.

**Comment by gorhill** [comment] 2015-03-02 01:05
Probably a remote server which was not repsonding. It happens often with EasyList server. There is a 30 second time out, then the UI should come back to life.

**Comment by Jekecy** [comment] 2015-03-02 02:07
Ok I couldn't help myself so I reset safari and ublock so I was effectively starting from scratch. I purged and re-updated my lists from Chrome, and did a full extension back-up. I used the back-up and loaded it to my Safari. Clicked "update now" and I'm back to the original issue. Been on the loading screen for 6 minutes now.

If it were truly one of the servers, I should be experiencing the same thing on Chrome. But I can purge and re-update almost instantaneously without issue. Definitely something exclusive to Safari.

**Comment by chrisaljoudi** [comment] 2015-03-02 02:08
@Jekecy again, sorry to hear about that.

What filter lists do you have enabled? Also, what version of µBlock is this occurring on?

**Comment by Jekecy** [comment] 2015-03-02 02:10
This is my current filters for both browsers:

http://cl.ly/image/1K3p1O1T0c2g/Image%202015-03-01%20at%209.09.13%20PM.png

I'm on the latest version (0.8.9.1)

**Comment by chrisaljoudi** [comment] 2015-03-02 04:14
@Jekecy can't reproduce, I'm afraid. To help reproduce, any other details that might be of interest?

**Comment by Jekecy** [comment] 2015-03-02 04:53
Unless there’s a log I can provide, I’m afraid not. Again I started from scratch by resetting all the settings on both the browser and extension. I’m using Yosemite, but that’s the other thing I can think of. It has to be something in the code conflicting with the update settings, because if I’d just left everything alone it was working fine. 

On March 1, 2015 at 11:15:02 PM, Chris Aljoudi (notifications@github.com) wrote:

@Jekecy can't reproduce, I'm afraid. To help reproduce, any other details that might be of interest?

**Comment by chrisaljoudi** [comment] 2015-03-02 04:57
@Jekecy alright.

To be sure, you can reproduce this without using the backup? In other words, does the issue occur if you just reset everything, install µBlock, choose the filters, and then try to update?

**Comment by Jekecy** [comment] 2015-03-02 05:06
Yep, I tried using the extension DL on your site as well as the one on Apple’s. Same results with a reset extension. 

I even tried only updating one list, (anti-adblocker) and it still gives the indefinite loading. If there’s any backup you have or you want me to try anything else out, let me know. I’d be more than willing to test it out. 

On March 1, 2015 at 11:58:02 PM, Chris Aljoudi (notifications@github.com) wrote:

@Jekecy alright.

To be sure, you can reproduce this without using the backup? In other words, does the issue occur if you just reset everything, install µBlock, choose the filters, and then try to update?

**Comment by chrisaljoudi** [comment] 2015-03-02 06:21
@Jekecy I went to a fresh machine (never installed µBlock before) with Safari 8 and did the following:
- Download and install µBlock from https://chrismatic.io/ublock/
- Enable the lists as you had in your screenshot
- "Apply Changes"
- Purge Caches
- Update

And that didn't result in the issue.

To make sure there's no miscommunication, are the steps above correct? If not, please share the full list of steps that does result in an issue.

Thanks for your patience, @Jekecy.

**Comment by gorhill** [comment] 2015-03-02 16:14
I suspect there must be some kind of error reported at the dev console for the extension, if so this would probably be the best hint as to what is happening.

**Comment by chrisaljoudi** [comment] 2015-03-02 18:49
@gorhill right, but I don't think one can't can inspect the dev console for the background page unless they install the extension from source.

@Jekecy if you can look in the console while on the preferences dashboard and the issue occurs, that might have some clues in it, though.

**Comment by Jekecy** [comment] 2015-03-03 03:20
Today I managed to get it up and working again, but that was only after deleting the extension, resetting the browser, and using Onyx to clean up any possible junk. After browsing regularly and slowly but surely turning some other extensions on and adding more filters, I went right back to square one with the indefinite loading. I tried repeating the process all over again but can’t manage to get the extension working once more.

Could be any slew of factors, and unfortunately i just don’t have the time to test out all of them one by one. I have Chrome to use so I should be fine. Maybe when the extension gets updated it’ll work itself out somehow. 

On March 2, 2015 at 1:49:15 PM, Chris Aljoudi (notifications@github.com) wrote:

@gorhill right, but I don't think one can't can inspect the dev console for the background page unless they install the extension from source.

@Jekecy if you can look in the console while on the preferences dashboard and the issue occurs, that might have some clues in it, though.

**Comment by chrisaljoudi** [comment] 2015-03-03 08:15
@Jekecy do you see any errors in the console when the update gets stuck? You can look at the console with the shortcut <kbd>⌘</kbd> + <kbd>alt</kbd> + <kbd>c</kbd> while you're in preferences and are experiencing the issue.

**Comment by Jekecy** [comment] 2015-03-04 02:05
As luck would have it, in the process of trying out this method and documenting from scratch, I got the extension to work again! All my other extensions are on, and the filters I want are active, so I’ll keep tabs on any changes. I’ll be sure to keep an eye on the error console as well. 

On March 3, 2015 at 3:15:36 AM, Chris Aljoudi (notifications@github.com) wrote:

@Jekecy do you see any errors in the console when the update gets stuck? You can look at the console with the shortcut ⌘ + alt + c while you're in preferences and are experiencing the issue.

**Comment by chrisaljoudi** [comment] 2015-03-04 07:46
Alright. Closing for now — please still feel free to comment when/if the issue comes up again or you find out anything.

**Closed as completed by chrisaljoudi** 2015-03-04 07:46 UTC
Labels: Can't reproduce
