### ISSUE TITLE
[firefox] about:healthreport cannot be opened in an existing tab

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#522] opened 2015-01-17 15:03 UTC
When tinkering with healthreport now, i just saw that you cannot open below url in an existing tab -
"about:healthreport"

Steps:
1. open google.com
2. Then open "about:healthreport"

Then you would see google in the popui:)

![ublock healthreport issue](https://cloud.githubusercontent.com/assets/779630/5789228/114d0116-9e88-11e4-992e-acf210e43f28.png)

<b>Edit:</b> I had almost this or similar issue during early preview stage, but was not able to figure out at that time. It came on fudzilla.com. (was seeing previous website entries in the dynamic filtering popui). Just wanted to bring it up.

**Comment by Mikey1993** [comment] 2015-01-17 15:11
I can't reproduce with the latest version (0.8.5.5) on FF Nightly (v38).
The page opens fine.

**Comment by harshanvn** [comment] 2015-01-17 15:14
Am on Firefox Stable (Windows 8.1, enabled dev theme, from about:config), using 0.8.5.5

<p>
browser.devedition.theme.enabled:true
devtools.theme: dark
</p>

@Mikey1993 Have you set dynamic filtering same as mine?

**Comment by gorhill** [comment] 2015-01-17 15:15
I could reproduce on Firefox. However I could not reproduce on Chromium (I used `about:blank`). Will keep investigating.

**Comment by harshanvn** [comment] 2015-01-17 15:17
And this doesn't happen with <b>about:</b>config

**Comment by Mikey1993** [comment] 2015-01-17 15:19
Actually, I **do** see some strange behavior if navigating to the "about:healthreport" from an existing tab and loading from a new tab, but I still can't get the page to draw blank and the popup doesn't include anything from google.

**Edit: Got the blank page, but don't have any google requests in the popup.**

**Comment by gorhill** [comment] 2015-01-17 15:23
I see that uBlock's `vAPI.tabs.onNavigation` is not called when `about:healthreport` is loaded in the tab, so this means uBlock has no way to know the tab changed. Probably something trivial but I will CC @Deathamns, he is likely to know immediately where is the quirk.

**Comment by gorhill** [comment] 2015-01-17 15:27
Yes, I see `onNavigation()` is [called only for `http[s]` pages](https://github.com/gorhill/uBlock/blob/master/platform/firefox/vapi-background.js#L314), while it should call for whatever so that uBlock can unbind it's data structure internally. This seems a trivial fix, but I prefer to let @Deathamns deal with it just to be sure there is no non-trivial consequences to the fix.

**Comment by harshanvn** [comment] 2015-01-17 15:29
Ok. Yes, this is not a big deal. It can definitely wait.
What i am wondering is, how come <b>about</b>:config is working. Perhaps onNavigation is called for it?

**Comment by gorhill** [comment] 2015-01-17 15:30
It should not, and I confirm `about:config` exhibits same problem.

**Comment by Deathamns** [comment] 2015-01-17 15:31
@gorhill Correct. If I recall correctly, I put that check there because pop-up blocking. I'll write a comment to the pop-up blocking issue...

**Comment by gorhill** [comment] 2015-01-25 16:30
Looks like this is fixed in 0.8.6.0, probably as a result of fixing #105.

**Comment by harshanvn** [comment] 2015-01-25 17:49
Yes. This is working fine now.
Not sure, if you want this to be closed, I will leave it for your choice.
Thanks.

**Closed as completed** 2015-01-25 19:27 UTC
