### ISSUE TITLE
Localization is tied to language used in browser

### ISSUE THREAD

**Issue by maxxyme** [uBlock-LLC/uBlock#676] opened 2015-02-03 19:06 UTC
(at least in Google Chrome) µBlock is in French because my Google Chrome is in French (I'm a French user and/or can't change the install at work) but I'd like to use µBlock in English.

How do I do that?

**Comment by Deathamns** [comment] 2015-02-03 19:15
Dupe of #622.

Your answer is in the referenced issue.

**Closed as completed by Deathamns** 2015-02-03 19:15 UTC

**Comment by maxxyme** [comment] 2015-02-04 10:04
OK thanks, didn't find this issue.

**Comment by gorhill** [comment] 2015-02-04 11:46
Apparently you can do this for Windows: https://support.google.com/chrome/answer/95416?hl=en.
