### ISSUE TITLE
Can't update filters in Safari

### ISSUE THREAD

**Issue by VadimMukhtarov** [uBlock-LLC/uBlock#964] opened 2015-03-08 09:11 UTC
uBlock 0.9.0.0 and previous version can't update filters (EasyList + RU AdList). Just a blue spinning wheel under mouse pointer after pressing the update button. I did permissions repair and reinstalled it, but still doesn't work. I use Safari 8.0.5. With uBlock 0.7.x all was good.

**Comment by chrisaljoudi** [comment] 2015-03-08 09:16
@VadimMukhtarov Hi!

Updating filter lists has worked quite reliably, so I couldn't reproduce the issue you described immediately.

t's worth noting: uBlock currently has a 30-second timeout if the remote server isn't responding to your requests.

Is the blue spinning wheel going away after 30 seconds or so? (Might have to wait more than that since multiple lists use the same server). If it is, then the remote server for the list (or your connection) might be having some issues.

Are EasyList and RU AdList the only two filter lists you have enabled?

**Comment by VadimMukhtarov** [comment] 2015-03-08 09:25
Hi. Yes, I use only 2 subscriptions. Just checked with default uBlock settings and got crash with EXC_BAD_ACCESS (SIGSEGV), KERN_INVALID_ADDRESS. And blue wheel spinning again after restart.
Here is crash log http://pastebin.com/7iZhW3Np

**Comment by chrisaljoudi** [comment] 2015-03-08 09:35
@VadimMukhtarov hmm. Is the crash still occurring? That error code in the context of Safari crashes seems to sometimes be caused by malware. Do you have "Genieo" installed? That causes the issue for some.

I just installed uBlock on a fresh Safari installation, all the default settings, and I couldn't reproduce the behavior you described.

**Comment by chrisaljoudi** [comment] 2015-03-08 09:38
@VadimMukhtarov so, when you're updating the filter lists and you get "stuck" (with the blue beach ball), can you please try <kbd>⌘</kbd> + <kbd>alt/option</kbd> + <kbd>c</kbd>, which will bring up the error console, and see if there's anything there?

Thanks.

**Comment by VadimMukhtarov** [comment] 2015-03-08 09:46
Console is clean, no errors or warnings. And I also 100% don't have any malware.

**Comment by chrisaljoudi** [comment] 2015-03-08 09:50
@VadimMukhtarov okay. Did you notice whether the freeze is disappearing after 30-60 seconds?

To help diagnose the issue further:
- Verify you still can't update the filter lists.
- Use `wget` or any other method on your same machine to try and download those two files:
  - `http://easylist-downloads.adblockplus.org/easylist.txt` <-- this is EasyList.
  - `http://easylist-downloads.adblockplus.org/advblock.txt` <-- this is RU AdList.

If you can download both of them successfully, but uBlock still freezes the update with **just those two enabled,** then it's almost certainly not a network issue.

**Comment by VadimMukhtarov** [comment] 2015-03-08 09:58
uBlock finally updated them after Safari restart, but still strange. Got another one crash with the same error. Looks like some regression or incompatibility with Safari 8.0.5.

**Comment by chrisaljoudi** [comment] 2015-03-08 10:05
@VadimMukhtarov 

> Looks like some regression or incompatibility with Safari 8.0.5.

I've been running this version of uBlock on Safari 8.0.5 (my personal machine) for days now — and haven't had a crash.

The reason I mention that is, it's not something that is inherently an obvious incompatibility between uBlock and Safari. There's **something** that's different between our two machines, and I hope you can help me diagnose that.

What kind of hardware are you facing this issue on? Do you have any guess/idea what seems to "cause" the crash — like, does it crash after you do something specific, or...?

Anything you think might be related would be much appreciated, @VadimMukhtarov.

**Comment by VadimMukhtarov** [comment] 2015-03-08 10:17
@chrisaljoudi I use the latest OS X 10.10.3 from App Store on MPB. All software from App Store and developers websites. No tweaks, plugins and cracks. These problems with uBlock started with 0.8.x branch. It would be nice if it had own log.

**Comment by chrisaljoudi** [comment] 2015-03-08 10:22
@VadimMukhtarov any other Safari extensions? (You can check in `Safari` -> `Preferences` -> `Extensions`).

And as far as the problems you mentioned started with 0.8.x, are you talking about the filter list updates, the crashes, or both?

**Comment by VadimMukhtarov** [comment] 2015-03-08 10:30
@chrisaljoudi I have only uBlock. Don't remember exactly about crashes, but problems with saving uBlock settings and filter updates was. Page with settings just stuck.

**Comment by gorhill** [comment] 2015-03-08 12:56
I don't know about the crash, but one thing that could be improved with the manual update (which I try to discourage by the way...) is to fetch lists one by one instead of all at once. Currently it's all at once, and for slow connections this could mean never being able to complete the download of any one list, when many lists are fetched at the same time.

Auto update will fetch the lists one by one, and compile them upon reception, so it is really the optimal way to update the lists.

**Comment by chrisaljoudi** [comment] 2015-03-09 04:30
@VadimMukhtarov I'd really like to diagnose this issue and stop the crashes from occurring for you, but I've been trying to trigger one here _all day_ and haven't been able to (including by enabling every  

Can you please share the full Safari crash report? Thank you.

**Comment by VadimMukhtarov** [comment] 2015-03-09 07:37
@chrisaljoudi here is 4 crash logs (2 from yesterday and 2 from today):
https://www.dropbox.com/s/7jxn84yqlkyh28o/Crash%20logs.zip?dl=0
And here is 2 videos with crashes:
https://www.dropbox.com/s/37dnjrjr3n7lpwa/Safari%20crash.mov?dl=0
https://www.dropbox.com/s/40ne53vpr5t0up0/Safari%20crash%202.mov?dl=0

**Comment by chrisaljoudi** [comment] 2015-03-09 21:47
@VadimMukhtarov reproduced! I have an idea on what the issue is; will get on it immediately.

FYI: for now, you can avoid the crashes by not updating the filter lists manually so frequently.

Will keep you updated.

**Comment by chrisaljoudi** [comment] 2015-03-10 01:18
Merged into #978.

**Closed as completed by chrisaljoudi** 2015-03-10 01:18 UTC
Labels: Combined with another issue

**Comment by gorhill** [comment] 2015-03-10 03:14
What's the issue?

**Comment by chrisaljoudi** [comment] 2015-03-10 03:16
@gorhill it's #978 — updating lots of filters quickly ends trying to use up a lot of RAM.

**Comment by gorhill** [comment] 2015-03-10 03:17
Ok, so this confirms pulling one by one with compilation upon reception is the way to go.

**Comment by chrisaljoudi** [comment] 2015-03-10 03:18
@gorhill yes, indeed.
