### ISSUE TITLE
No menu with navigation bar disabled on Firefox

### ISSUE THREAD

**Issue by eduardoeae** [uBlock-LLC/uBlock#1295] opened 2015-04-21 10:25 UTC
I use Vimperator and, as I have no need, don't usually show the navigation bar.
But if it is disabled uBlock shows no menu. Nothing pops up when I click in the icon.

**Comment by benoit-pierre** [comment] 2015-04-21 10:31
Duplicate of issue #720, see comments for a workaround.

**Closed as completed** 2022-09-08 21:24 UTC
