### ISSUE TITLE
[safari] ublock pannel truncated

### ISSUE THREAD

**Issue by cqst** [uBlock-LLC/uBlock#1080] opened 2015-03-23 19:46 UTC
![capture d ecran 2015-03-23 a 20 47 16](https://cloud.githubusercontent.com/assets/4339847/6789072/e573fdda-d19d-11e4-83db-afb8305835a4.png)
running 0.9.2.0 and when I click on ublock button pannel is now truncated.
french language
safari 8.0.4

my 2 cents..

**Comment by gorhill** [comment] 2015-03-23 19:58
Duplicate of #1066. Fixed in 0.9.2.1.

**Closed as completed by gorhill** 2015-03-23 19:58 UTC
