### ISSUE TITLE
Disabling web fonts breaks interface

### ISSUE THREAD

**Issue by freegigi** [uBlock-LLC/uBlock#1034] opened 2015-03-16 16:35 UTC
Disabling web fonts in Firefox (gfx.downloadable_fonts.enabled false) makes ublock look really bad. I was not expecting those symbols to be web fonts. I hope you can fix this.

Thank you!

![screenshot_2015-03-16_18-26-30](https://cloud.githubusercontent.com/assets/6600835/6670946/8c164a06-cc0a-11e4-9dd6-293939d7641a.png)

**Comment by freegigi** [comment] 2015-03-16 16:38
I checked --disable-remote-fonts in chromium, same issue.

**Comment by Deathamns** [comment] 2015-03-16 16:38
Duplicate of #629?

**Comment by freegigi** [comment] 2015-03-16 16:51
Yes, probably duplicate. Thank you for pointing me in the right direction. From that thread I found out that the font is Font Awesome. I installed it system-wide and I can disable web fonts without breaking the interface. Kind of awkward, but it works.

I still feel that using svg or some other image format is better.

**Comment by chrisaljoudi** [comment] 2015-03-16 16:54
https://bugzilla.mozilla.org/show_bug.cgi?id=789788

**Closed as completed** 2015-03-16 19:32 UTC
