### ISSUE TITLE
uBlock's menu doesn't apear when address bar is hidden

### ISSUE THREAD

**Issue by AeliusSaionji** [uBlock-LLC/uBlock#1484] opened 2015-07-06 23:43 UTC
I use pentadactyl, and hide most UI elements. I tried placing uBlock on the lower address bar, but quickly discovered that it will not work this way. For whatever reason, the firefox address bar must be visible for uBlock to show its menu.

**Comment by AlexVallat** [comment] 2015-07-07 07:27
Duplicate of #720 

Quick fix: set the `about:config` preference `extensions.ublock.forceLegacyToolbarButton` to true and restart the browser. Then use Customize to put the toolbar button wherever on whatever visible bit of UI you have left.

**Closed as completed by AlexVallat** 2015-07-07 07:27 UTC
Labels: Duplicate
