### ISSUE TITLE
[Firefox] Pop-up menu doesn't show when using prospector oneliner add-on

### ISSUE THREAD

**Issue by volia1** [uBlock-LLC/uBlock#804] opened 2015-02-15 17:31 UTC
Actually I thought it's normal since oneliner had that bug, but now it's updated and GM&Stylish can produce their pop-up menu (Don't test another add-ons yet). But when I clicked uBlock, it couldn't show the pop-up menu.
Can you fix this?
I'm using 37.0a2 on win8.1 anyway.

Thanks

**Comment by gorhill** [comment] 2015-02-16 13:43
Duplicate of #549?

**Comment by volia2** [comment] 2015-02-17 09:49
It's different add-ons. Oneliner is mozilla's add-ons, but Pentadactyl isn't. Also I tried using the code in #549, and it doesn't work.
Anyway these are GM's and Stylish's pop-up menu when using oneliner http://puu.sh/g0H1k.png http://puu.sh/g0H1T.png . And this is ublock http://puu.sh/g0H2e.png

**Closed as completed** 2022-09-08 21:25 UTC
