### ISSUE TITLE
about Element pick shortcut

### ISSUE THREAD

**Issue by dupontjoy** [uBlock-LLC/uBlock#896] opened 2015-02-27 08:05 UTC
Just turn to uBlock from ABP. Really like the compact design. Everything is great except for the element pick. Could someone tell what is the shortcut to pick element instantly, or is there a way to invoke element picking via Keychanger.uc.js. For ElementHidingHelper, this code ( keys['Ctrl+F1'] = "window._ehhWrapper.toggleSelection();"; ) can set a shortcut. Thanks

**Comment by gorhill** [comment] 2015-02-27 11:00
Duplicate of #256.

**Closed as completed by gorhill** 2015-02-27 11:00 UTC
