### ISSUE TITLE
[Firefox] Sandwich/Hamburger menu becoming blank for some windows

### ISSUE THREAD

**Issue by Caspy7** [uBlock-LLC/uBlock#638] opened 2015-01-29 12:10 UTC
After installing and using uBlock for a while I noticed that I would click on the sandwich menu (the three bars on the upper right) and the menu contents would appear for a second and then it would close. When I click again the entire contents of the menu has disappeared: http://i.imgur.com/1wcUa5V.png

Other windows would be unaffected, but eventually the issue occurs for them too.
If I disable uBlock, the problem goes away. Reenabling it resets the timer and it eventually happens again.

I should probably redefine "eventually" as I just had it occur for 2 out of 2 different windows when I tested.  So it's quite irritating.
If it's relevant, I have the uBlock icon placed in the menu.

**Comment by Deathamns** [comment] 2015-01-29 12:47
> If it's relevant, I have the uBlock icon placed in the menu.

I wasn't very clear about this, but when I said "may mess it up" [here](https://github.com/gorhill/uBlock/releases/tag/0.8.5.4-beta.0), I was talking about this issue.

**Comment by rodalpho** [comment] 2015-01-29 16:14
This happened to me also in older versions of uBlock and Firefox, but using the most recent releases in Fx36 beta, the sandwich menu now works fine. It's either a Fx35 issue or fixed in recent uBlock releases.

**Comment by Caspy7** [comment] 2015-01-29 23:30
Sorry, I should have mentioned I'm currently using the (currently) most recent version of uBlock 0.8.6.0 in Firefox 37.0a2 (aurora/dev edition).

**Comment by rodalpho** [comment] 2015-01-30 01:40
Weird. I can't reproduce now (and again, I did have this exact problem last week). Does it happen in a fresh profile?

**Comment by Deathamns** [comment] 2015-01-30 07:20
This should happen only from Firefox 36 by the way.
Edit: it's probable that this is a browser issue.

**Comment by Caspy7** [comment] 2015-02-02 00:48
If this is a browser issue and we can distill it down, we can file a bug.
In the meantime perhaps we can look into a workaround.

**Comment by Deathamns** [comment] 2015-02-02 11:03
I won't bother reporting it because I don't know if it's really a browser issue or not, and we need to implement the toolbar/popup in a different way anyway (to solve a couple of problems, which I listed in the referenced issue above).
But If you want to, then the cause for the menu collapsing is probably [setting the style](https://github.com/gorhill/uBlock/blob/77044c6c98d9f2a8e01dd301712c59edd7933284/platform/firefox/vapi-background.js#L1380) for an anonymous element.

**Comment by BubiBalboa** [comment] 2015-02-09 14:49
I keep having the same issue with version 0.8.7.0 on FF 36.0 beta and the uBlock icon in the hamburger menu. Works fine on tabs where nothing is blocked like the speeddial and some websites.

**Comment by gjallarhorn** [comment] 2015-02-16 23:29
A temporary workaround for this is to disable the "Show the number of blocked requests on the icon" option.

**Comment by Caspy7** [comment] 2015-02-16 23:37
@gjallarhorn Thanks!  If I'd thought about it and known about the option this should have been obvious.

For those visiting and wishing for a shortcut to your options (Firefox only probably) paste this into your location bar:
chrome://ublock/content/dashboard.html

**Comment by garyking** [comment] 2015-02-25 18:24
@gjallarhorn that workaround does not work for me, with uBlock 0.8.8.0 on Firefox 36 on a Mac. 

When I move the uBlock icon to the Menu, it changes from red to grey, which seems to indicate that it's disabled, even though it still works. I'm not sure if this is related to the problem though.

**Comment by Deathamns** [comment] 2015-02-25 18:38
@GaryKing Refresh the page after you disabled the mentioned setting, and moved the button to the menu-panel.

**Comment by garyking** [comment] 2015-02-25 18:43
@Deathamns I am able to fix the problem immediately after performing the proper steps, but once I restart the browse, then I immediately open and close the Menu a few times, then the problem immediately occurs again.

**Comment by BubiBalboa** [comment] 2015-02-25 19:37
@GaryKing Try disabling Fanboy’s Social Blocking List. That did it for me.

**Comment by Deathamns** [comment] 2015-02-26 06:26
@GaryKing If I disable the option, refresh the page, the menu will work even after I restart the browser.

**Comment by garyking** [comment] 2015-02-26 07:26
@Deathamns Sorry but I'm not seeing that. I'm also testing in a new profile. I disable the option (in fact, I've already got the option disabled for weeks in my default profile), refresh the page, and the problem disappears. But when I launch the new profile again, all I have to do is click the Menu open and close a few times, then the problem re-appears.

**Comment by Deathamns** [comment] 2015-02-28 12:04
Possible fix in 9fe8f414.
I still don't know why the panel collapses, but as a temporary fix, now the badge will be disabled if someone places the icon in the menu-panel.

**Comment by ArsalanDotMe** [comment] 2015-03-05 04:18
I am certain this is a browser issue and still exists in Firefox Developer Edition 37.0a2.
This issue not only happens with uBlock, but also Pushbullet. I'm guessing it has to do with the badge.

**Closed as completed** 2022-09-08 21:25 UTC
