### ISSUE TITLE
[Firefox] Feature Request: Pale Moon Support

### ISSUE THREAD

**Issue by lewisje** [uBlock-LLC/uBlock#518] opened 2015-01-17 10:35 UTC
Now that the Firefox version has a minimal level of support for Firefox 24, it appears feasible to support Pale Moon, which was forked from Firefox 24 and has GUID `{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}`; the changes necessary for this extension to work may be the same as the ones made in the Pale Moon community's fork of Adblock Plus, known as Adblock Latitude: http://forum.palemoon.org/viewtopic.php?f=15&t=6732

**Comment by gorhill** [comment] 2015-01-17 10:49
I don't know how @Deathamns feels about this, but my own feeling is that whoever is ready to take care of a PaleMoon version should do so in its own [platform-specific branch](https://github.com/gorhill/uBlock/tree/master/platform), to avoid having the Firefox-specific code from being "polluted" with legacy code, exception code paths, etc. which would make it more difficult to maintain.

Another advantage is that any change in the Firefox-specific code will only affect Firefox version, so no need to test the effect of changes for PaleMoon, and vice versa.

**Comment by Deathamns** [comment] 2015-01-17 13:46
Basically if we make it compatible from Firefox 24 (or around), then Pale Moon, SeaMonkey, and others will be automatically supported.
As I said at the SeaMonkey request, the only problem is the toolbar button and the popup.
If someone builds it from the current master, then it can be installed for the requested browsers too (and everything works except the mentioned problems).

**Comment by JeremyWW** [comment] 2015-02-13 18:09
@Deathamns Yep, that's what it needs. I'd love to have this sorted as I'm a keen user of dynamic filtering and recently switched to Pale Moon x64.

**Comment by gorhill** [comment] 2015-03-18 17:10
I added a workaround which enables to access the popup UI through the network request log tool:

![a](https://cloud.githubusercontent.com/assets/585534/6714596/7ae6ea04-cd6f-11e4-931b-1ebf515a6299.gif)

This was sort of trivial to add, and a natural place to add such button, since there is already a selector in there to select which web page is being inspected. I did not try it on Palemoon as I do not have it installed, but if the missing toolbar button was the only issue with Palemoon, then the solution here should work fine. If it does, I think the issue could be marked as resolved.

The popup in there is sticky by the way, i.e. it stays open as long as it's not toggled off.

**Comment by Snapy** [comment] 2015-03-18 18:13
Tested and confirmed working with Palemoon 25.3

**Comment by radry** [comment] 2015-03-18 20:54
Palemoon 25.3 here. I don't have any button in the network monitor tool?? Whats the use of the button there anyways? I can access the options trough the addons screen. I want a toolbar button to enable/disable it on some website on the fly withouth having to go trough all settings.

**Closed as completed** 2022-09-08 21:25 UTC
Labels: Available
