### ISSUE TITLE
uBlock doesn't show notification icon (popup ui) on Pale Moon

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#966] opened 2015-03-08 13:03 UTC
Dear all,

formerly I used the original Mozilla Firefox (Fx). Currently I use a derivative: Pale Moon http://www.palemoon.org/ it's Open Source as well and it's based on the original Fx, but optimized and compiled for modern x64 systems. And further, it doesn't use Australis.

Maybe the lack of Australis is the reason that the uBlock/µBlock notification icon (popup user interface) like https://raw.githubusercontent.com/gorhill/uBlock/master/doc/img/popup-1.png doesn't show up.

Is it possible to fix this issue? Thank you for any advice or help.

gunnersson

**Comment by gorhill** [comment] 2015-03-08 13:06
Duplicate of #518.

**Closed as completed by gorhill** 2015-03-08 13:06 UTC
