### ISSUE TITLE
Incompatibility With Lastpass

### ISSUE THREAD

**Issue by gary-hammer** [uBlock-LLC/uBlock#1446] opened 2015-06-12 14:24 UTC
Causes lastpass to not function properly. When you have a login dialog lastpass usually has an asterisk next to the username and password. When you click the asterisk, you get the logins lastpass has for the site and you choose one and are logged in.
With uBlock active, this does not work, the asterisk turns to an X when clicked.

**Comment by publicarray** [comment] 2015-07-14 15:56
Please see [CONTRIBUTING.md](https://github.com/chrisaljoudi/uBlock/blob/master/CONTRIBUTING.md#what-to-include)
specifically can you post uBlock filter lists and settings different from the default? Also the browser version please?

**Comment by publicarray** [comment] 2015-07-18 05:36
I use lastpass with ublock everyday without problems

**Comment by vanontom** [comment] 2015-07-31 16:36
I am also experiencing this problem with some sites. Didn't realize it was a conflict with uBlock.

The LastPass field buttons ("asterisk" logo) may not show up, clicking in field makes it show, but does not auto-fill. Clicking again on button for drop-down menu does not work at all (just toggles into "x" and back).

Manually using LastPass menu to "show matching sites" and auto-fill works, thankfully as temporary workaround. Even better, setup simple hotkey in LastPass preferences to "fill in next login", makes this problem easily tolerable. With uBlock off, everything works fine. Played with uBlock settings (disabling features, filters) to no avail.

uBlock 0.9.5.0, default settings. Firefox 39.0, disabled other extensions. LastPass 3.2.16. Windows 8.1.

Example site with problem: https://www.adorama.com

**Comment by publicarray** [comment] 2015-08-01 06:29
I have been unable to reproduce this with uBlock 0.9.5.0 (defaults), LastPass 3.2.16 & FF 39.0 I tried it on both Win 8.1 and Mac OS X 10.10.4. For me, the behaviour is the same with and without uBlock: http://youtu.be/iBr5kLDiwaU

**Comment by vanontom** [comment] 2015-08-01 14:38
publicarray: Thank you very much for helping with this, going through the trouble to reproduce this problem. I've already spent a bit of time trying to figure it out, and now with your results, I assume it is some rare problem with my (and few other's) installations, which will be fixed when freshly reinstalled.

It does not affect most sites, and the hotkey makes it very tolerable, so that's that I guess. Thanks again.

**Comment by publicarray** [comment] 2015-08-01 15:22
No problem @vanontom, If you are willing to test this further I suggest you [create a new firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles). That way you are essentially in a new environment and you test any settings / plugins from a clean slate. Your settings and plugins remain safely in your main profile (you can switch between them using the profile manager).

**Comment by takamaka** [comment] 2015-08-17 07:30
I use lastpass and I have exactly the same problem on many sites i use, for some official sites i just fully disable ublock for all the website and thats ok.

**Comment by publicarray** [comment] 2015-08-18 04:38
@takamaka can you give us an example?

**Comment by takamaka** [comment] 2015-08-18 07:08
sorry for the term many, for now I retrieved only one example which is my intranet (certainly due to specific login webpage)
with adblock there is no need to add this website to whitelist
but as there is no ad, it is not a problem

Otherwise I was obliged to deactivate ublock on this site http://support.amd.com/fr-fr/download
to be able to select manually a graphic card driver (the button display results does not work with ublock).

I hope this could help to avoid future website misfunctionning :)

thks

**Comment by publicarray** [comment] 2015-08-18 07:47
@takamaka your issue is not related to lastpass. However you can add the following to your filters to counter `||www.googletagmanager.com^` found in `hpHosts’ Ad and tracking servers` and `||www.google-analytics.com^` found in `hpHosts’ Ad and tracking servers` & `MVPS HOSTS`

```
! 18/08/2015, 05:40:00 pm support.amd.com/en-us/download 
! fix not displaying results when manually selecting a driver
@@||googletagmanager.com/gtm.js$domain=support.amd.com
@@||google-analytics.com^$domain=support.amd.com
```

To @chrisaljoudi @gorhill maybe add this to uBlock's unbreak filter?

**Closed as completed** 2022-09-08 21:24 UTC
