### ISSUE TITLE
[enhancement] add/edit filters from the request log

### ISSUE THREAD

**Issue by ekerazha** [uBlock-LLC/uBlock#1047] opened 2015-03-18 13:59 UTC
In AdBlock Plus you can add rules this way:
- Open blockable items list
  ![ABP blockable items](https://i.stack.imgur.com/3ASfY.png)
- Double click an item to add/edit a filter
  ![ABP filter rule](http://img.snaphow.com/wp-content/uploads/images/Block-Survey-PopUps-with-Adblock-Plus.png)

Would it be possible to add something similar to uBlock so we can add/edit filters from the request log?

**Comment by gorhill** [comment] 2015-03-18 14:00
Duplicate of #68.

**Closed as completed by gorhill** 2015-03-18 14:00 UTC

**Comment by gorhill** [comment] 2015-03-18 14:01
For the specific example you give above -- blocking `www.cpalead.com` -- [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide) would work.

**Comment by ekerazha** [comment] 2015-03-18 19:52
@gorhill I just took some random images from the web :-)
