### ISSUE TITLE
[Firefox] Pop-up menu doesn't show properly when ublock icon is in hamburger icon.

### ISSUE THREAD

**Issue by volia2** [uBlock-LLC/uBlock#857] opened 2015-02-21 18:34 UTC
![screenshot 43](https://cloud.githubusercontent.com/assets/10745233/6315392/e61328a6-ba32-11e4-9b30-8ce2a6e500ba.png)

I don't use oneliner add-ons anyway.

**Comment by gorhill** [comment] 2015-02-21 21:12
Duplicate of #505.

**Closed as completed by gorhill** 2015-02-21 21:12 UTC
