### ISSUE TITLE
Feature Request: Default to off

### ISSUE THREAD

**Issue by raygan** [uBlock-LLC/uBlock#944] opened 2015-03-05 16:37 UTC
I'd like to have the blocking default to off for each given domain, and then allow me to enable it on a site by site basis as I encounter pages which annoy me, as opposed to the reverse.

I didn't see this option in the settings, though it's possible I missed something.

**Comment by gorhill** [comment] 2015-03-05 16:39
Duplicate of #177.

**Closed as completed by gorhill** 2015-03-05 16:39 UTC
