### ISSUE TITLE
uBlock taking up lots of RAM on Firefox

### ISSUE THREAD

**Issue by starbaki** [uBlock-LLC/uBlock#929] opened 2015-03-04 00:20 UTC
Today I switched from AdBlock Plus to uBlock because I heard it would get rid of the memory problem. With ABP, Firefox's RAM got up to 2.5 million.
i disabled it while looking for a different adblocker, and firefox stayed at a steady 300k, which is ideal.

now that I have uBlock, it's taking up 1.7 million and my RAM (6gb) is at 96%? closing firefox fixes the problem so I know it's not anything else. How do i prevent uBlock from taking up so much memory? Is there something else I'm doing wrong? 
my computer is very slow and almost unusable, and i need it for work please help..

**Comment by gorhill** [comment] 2015-03-04 00:29
>  Is there something else I'm doing wrong?

Yes.

You first need to **prove** uBlock is the cause of your memory problem.

Reproduce the memory problem, then open a tab on `about:memory`, click first "Minimize memory usage" to force garbage collection, then click "Measure". Report the output here. Ensure the lines I highlighted in the screenshot below are visible in your report:

![d](https://cloud.githubusercontent.com/assets/585534/6475735/920542ca-c1db-11e4-805e-883fcfe142b9.png)

**Comment by starbaki** [comment] 2015-03-04 00:48
it was really long, I had to crop it to show the lines needed.

Sorry about the blackouts by the way, I'm just a little paranoid. If it's really necessary I can share them: the first two are youtube videos, the next three are links to my Tumblr page, the next is a user tracker and the last one is my school's website.

http://i.gyazo.com/48aafe163a9448d717f4b2a6e1aaf3e0.png
http://i.gyazo.com/0987b8d87b9890d7873c31c588824044.png

**Comment by gorhill** [comment] 2015-03-04 00:54
I see uBlock taking a grand total of 33 MB, out of 663 MB in explicit allocations. Nowhere near your original statement of 1.7 GB. So you did not reproduce the bug.

**Comment by gorhill** [comment] 2015-03-04 01:06
I will have to close the issue if you do not provide something to substantiate your "uBlock taking up so much memory". Given you would be the first person to report such a problem, you need to come forward with something, and what you provided so far disprove your own claim.

**Comment by gorhill** [comment] 2015-03-04 03:22
Open it again when you have something more substantial than a shocking headline.

**Closed as completed by gorhill** 2015-03-04 03:22 UTC
Labels: Can't reproduce
