### ISSUE TITLE
[Firefox Mobile] Number of connected domains makes no sense

### ISSUE THREAD

**Issue by WalterWW** [uBlock-LLC/uBlock#1019] opened 2015-03-15 12:33 UTC
Sometimes the number displayed under 'domains connected' is too big:

http://i.imgur.com/V29r3sM.jpg

I've also seen 3 of 2 as well as 1 of 0.

(The above screenshot is after opening this via reddit: http://i.imgur.com/aq9WtgZ.gifv)

**Comment by gorhill** [comment] 2015-03-15 13:03
Side effect of fix for #759.

**Comment by gorhill** [comment] 2015-03-15 13:05
I get "1 out of 1" for <http://i.imgur.com/aq9WtgZ.gifv>.

**Comment by gorhill** [comment] 2015-03-15 13:09
Can I have the URL on reddit through which http://i.imgur.com/aq9WtgZ.gifv was opened?

**Comment by WalterWW** [comment] 2015-03-15 13:21
opened via https://www.reddit.com/.compact

**Comment by gorhill** [comment] 2015-03-15 13:43
Can I see the content of the dynamic filtering pane for when that issue occurs?

**Comment by WalterWW** [comment] 2015-03-15 13:50
At that time I didn't have dynamic filtering enabled, so it was purely adblock filters.

In the meantime I've played around with it some more and have also enabled dynamic filtering. This is what it looks like with df enabled:

http://i.imgur.com/G44ZjPe.jpg

**Comment by gorhill** [comment] 2015-03-15 14:01
This is really difficult, I would need to step through the code, but then I have no mobile device.

**Comment by gorhill** [comment] 2015-03-15 14:11
I am going to try using [this thing](http://developer.android.com/tools/devices/emulator.html).

**Comment by WalterWW** [comment] 2015-03-15 16:21
Hmm. A few things I've noticed so far:
- The issue occurs when a link gets opened in a new tab (I have reddit set to open links in a new tab)
- But it doesn't happen when manually selecting 'open in new tab' from the firefox context menu after long pressing the link (funnily enough it often shows 0 out of 0 domains when doing this though, so there's a bug here somewhere too)
- After reloading the page, the number of connected domains displays correctly again

edit: I've also noticed that when a link opens in a new tab, the new tab shows    about:blank for a moment before loading the page. Maybe ublock adds that to the connected domains counter for some reason?

**Comment by AlexVallat** [comment] 2015-03-15 16:32
@gorhill I've fixed a bunch of new tab issues with #1021, it might fix this too. I haven't been able to reproduce the original issue though, I think I might need a more static example than reddit to try it on.

**Comment by WalterWW** [comment] 2015-03-15 16:44
Static example to reproduce the issue:
- go to https://duckduckgo.com/?q=refcontrol&kn=1 (the kn=1 attribute should make it open links in a new window)
- click on the second search result to open stardrifter.org/refcontrol/

Btw: I just followed the above and it showed 1 out of 1, then I tried it again and it showed 2 out of 1, so no idea how consistently that happens.

**Comment by AlexVallat** [comment] 2015-03-15 16:53
Thanks, with those steps I get 2 out of 1 domains connected. Applying the fix I mentioned I get 1 out of 1, so it looks like it's the same root cause.

**Comment by gorhill** [comment] 2015-03-15 18:41
Fixed by #1021.

**Closed as completed by gorhill** 2015-03-15 18:41 UTC
