### ISSUE TITLE
Update µBlock Firefox add-on page

### ISSUE THREAD

**Issue by devnoname120** [uBlock-LLC/uBlock#1123] opened 2015-03-29 23:25 UTC
Hello,

Would it be possible to update the [Firefox add-on page](https://addons.mozilla.org/en-US/firefox/addon/ublock/) every time a release is made?

The releases on Github don't have an auto-update feature, and the add-on page is outdated, so I need to manually install the new version from Github.

**Comment by gorhill** [comment] 2015-03-29 23:29
Duplicate of #1006.

**Closed as completed by gorhill** 2015-03-29 23:29 UTC

**Comment by devnoname120** [comment] 2015-03-29 23:35
@gorhill Why not adding a `<updateURL>` in [install.rdf](https://github.com/gorhill/uBlock/blob/415846e3266a051de5e4c2ec08cd03a57b1aacff/platform/firefox/install.rdf)? It would be set to something like https://ublock.github.io/latest.rdf when released on Github.
