### ISSUE TITLE
Background redirects not blocked

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1294] opened 2015-04-21 08:40 UTC
[Moved to https://github.com/gorhill/uBlock/issues/99]

**Comment by chrisaljoudi** [comment] 2015-04-21 22:09
Please provide a specific test case where this occurs (popups not being blocked), and we can more appropriately diagnose the issue then.

**Comment by flyingzebras** [comment] 2015-04-22 08:46
@chrisaljoudi

[also reported in https://forums.lanik.us/viewtopic.php?f=62&t=21495&p=69619#p69619]

The Pornhub NETWORK is full of popup redirects that appear in uBlock with EasyList enabled, but they are blocked by Adblock Plus. I'm not sure why Adblock Plus and uBlock behave different in this regard but maybe you know?

Pornhub NETWORK domains with popups:
pornhub.com
redtube.com
youporn.com
tube8.com
pornmd.com
spankwire.com
keezmovies.com
xtube.com
extremetube.com
gaytube.com

**Comment by flyingzebras** [comment] 2015-04-25 14:57
@chrisaljoudi

[also reported in https://forums.lanik.us/viewtopic.php?f=62&t=21495&p=69619#p69619]

Pornhub NETWORK domains
Note that most of the sites have sub domains for languages eg tube8 is registered as tube8.com,tube8.fr,tube8.es but also as de.tube8.com. This is the complete list of Pornhub NETWORK domains. Please revise EasyList for any filter that can be used to include them. This huge project will pay off in long-term but it may take long time to finish. However, you can save this list as reference.

    m.pornhub.com
    m.redtube.com
    m.youporn.com
    m.tube8.com
    m.pornmd.com
    m.spankwire.com
    m.keezmovies.com
    m.xtube.com
    m.extremetube.com
    m.gaytube.com
    de|fr|es|it|pt|pl|ru|jp|.pornhub.com
    fr|de|es|it|nl|tr|pl|ru|.youporn.com
    de|.tube8.com
    tube8.com,tube8.fr,tube8.es

**Comment by gorhill** [comment] 2015-04-25 15:05
@flyingzebras What browser/version? This is important to mention.

**Comment by flyingzebras** [comment] 2015-04-25 16:02
@gorhill IceCat 31.6.0 (based on Firefox ESR 31.6.0).

**Comment by gorhill** [comment] 2015-04-25 16:14
@flyingzebras You also need to provide URLs from where the popups occur. The first thing to do for a dev is to _reproduce_ the problem, without this, no fix possible. You enumerate URLs of popups, but from where did you get them?

**Comment by flyingzebras** [comment] 2015-04-25 16:23
@gorhill I updated the information above. Thank you.

**Comment by gorhill** [comment] 2015-04-25 16:46
> full of popups that appear in uBlock with EasyList enabled, but they are blocked by Adblock Plus

I am skeptical of this. I tested one site, and I did get a "popunder" (which is also an issue for ABP). However, it happens only once, apparently the site sets a cookie and once this cookie is present it won't trigger another popup. Try your test again with ABP but first **clear all the cookies** for the site, and then open a page where the popups occur. If uBlock and ABP have the same filter lists enabled, there won't be more popups with uBlock, or less popups with ABP.

The popup blocker in uBlock is pretty solid, it passes tests that ABP won't pass, for example, ABP fails 9. and 10. [here](http://raymondhill.net/ublock/popup.html). So it's all in the filters, and it's also how you conduct your tests: you may get a popup with the first blocker you test, then no popup with the other one on the same page, because the page sets cookies (probably to delay the next popup, to not badger the users with too many popups.)

**Comment by flyingzebras** [comment] 2015-04-25 17:56
@gorhill Ok, but the popups I encounter should still be blocked.

**Comment by gorhill** [comment] 2015-04-25 18:00
The ones you encounter are probably the popunder ones, which are not currently blocked by ABP or uBlock:

uBlock: https://github.com/gorhill/uBlock/issues/99
ABP: https://issues.adblockplus.org/ticket/2095

**Comment by flyingzebras** [comment] 2015-04-25 18:05
@gorhill So what do you suggest?


Should I file these popunder ones in that thread?

**Comment by flyingzebras** [comment] 2015-04-25 18:15
@gorhill Thank you for adding this issue to https://github.com/gorhill/uBlock/issues/99

Should I add this to block pop under for the domains listed in this issue?:

no-popups: pornhub.com true
no-popups: redtube.com true
no-popups: youporn.com true
no-popups: tube8.com true
no-popups: pornmd.com true
no-popups: spankwire.com true
no-popups: keezmovies.com true
no-popups: xtube.com true
no-popups: extremetube.com true
no-popups: gaytube.com true

**Comment by gorhill** [comment] 2015-04-25 20:46
You can't block popunder currently, that's why it still is an open issue.

**Comment by flyingzebras** [comment] 2015-04-26 08:13
@gorhill Thank you.

**Comment by flyingzebras** [comment] 2015-04-26 11:14
Popup domain: tube8.com
Popup URL: http://www.casino.com/sv/media/wide_200p/slots/bonus_bears/?b=med_200p&SID=209518&p=1
Popup position: left tab

**Comment by gorhill** [comment] 2015-04-26 11:35
I tried `tube8.com`, and a popup to `ebocornac.com` was blocked, by filter `|http://*?id=$domain=tube8.com`. So it seems to me the URL of your popup is not matched by EasyList, this is something you should report to EasyList maintainers.

**Comment by flyingzebras** [comment] 2015-04-26 11:41
@gorhill Thank you. I added that to https://forums.lanik.us/viewtopic.php?f=62&t=21495&p=69619#p69619 - This link is used to file the corresponding problem to EasyList. Please have a look and/or participate.

**Comment by flyingzebras** [comment] 2015-04-26 12:07
@gorhill I would really appreciate if you participated in https://forums.lanik.us/viewtopic.php?f=62&t=21495&p=69619#p69619

**Comment by gorhill** [comment] 2015-04-26 12:18
Looking at it, your popup with URL `http://www.casino.com/sv/media/wide_200p/slots/bonus_bears/?b=med_200p&SID=209518&p=1` should have been blocked by filter `|http://*?*=*&$popup,third-party,domain=tube8.com` in EasyList. Are you saying that popup was not blocked by uBlock? If so, you will have to enumerate your filter lists, your custom filters, whether dynamic filtering is enabled, and if so what rules are in use on `tube8.com`, also, your whitelist directives.

**Comment by flyingzebras** [comment] 2015-04-26 12:40
@gorhill Do I have to use both

|http://*?*=*&$popup,third-party,domain=tube8.com
|http://*?id=$domain=tube8.com


to block popup/popunders from tube8.com?

**Comment by flyingzebras** [comment] 2015-04-26 12:44
@gorhill
How do I block all these domains with EasyList (please modify):

no-popups: pornhub.com true
no-popups: redtube.com true
no-popups: youporn.com true
no-popups: tube8.com true
no-popups: pornmd.com true
no-popups: spankwire.com true
no-popups: keezmovies.com true
no-popups: xtube.com true
no-popups: extremetube.com true
no-popups: gaytube.com true

**Comment by flyingzebras** [comment] 2015-04-26 12:52
@gorhill Where do I find a list of predefined variables for Adblock Plus?

I do not find $domain or $popup in https://adblockplus.org/en/filters


This is EasyList related and EasyList is part of uBlock.

**Comment by gorhill** [comment] 2015-04-26 12:55
@flyingzebras You are making this very difficult by not _focusing_ on a very specific issue, and by not providing information _only_ on what I am asking [here](https://github.com/chrisaljoudi/uBlock/issues/1294#issuecomment-96372114). So please, focus only on this:

Your issue:
- URL: `tube8.com`
- URL of not blocked popup: `http://www.casino.com/sv/media/wide_200p/slots/bonus_bears/?b=med_200p&SID=209518&p=1`

Can you confirm this is your issue?

If so, please provide the details I asked above, and _only_ these. All else is noise making the whole thing very confusing to follow.

**Comment by flyingzebras** [comment] 2015-04-26 12:59
@gorhill:

URL: tube8.com
URLs of unblocked popups:
ebocornac.com/fp.engine?id=b170c29d-8fd6-4237-bba5-ccbdf691c081&rand=24598&ver=asynch&time=-120&referrerUrl=http%3A%2F%2Fwww.tube8.es%2F&subId=&abr=true&hosted=true
which redirects to
https://casino-x.com/?partner=p13186p24926p73de&promo=cx_doublepimp_main_white_se_Tube8

**Comment by gorhill** [comment] 2015-04-26 13:01
> If so, you will have to enumerate your filter lists, your custom filters, whether dynamic filtering is enabled, and if so what rules are in use on tube8.com, also, your whitelist directives.

**Comment by flyingzebras** [comment] 2015-04-26 13:06
@gorhill I'm using uBlock 0.9.1.0 with default settings ("Reset to default settings..." clicked) with updated filter lists ("Update now" in 3rd-party filters clicked).

**Comment by gorhill** [comment] 2015-04-26 13:12
> IceCat 31.6.0  ... uBlock 0.9.1.0

As said, I can't reproduce your issue, popups are blocked when I try to reproduce. However that is with latest release of uBlock and latest release of Firefox.

**Comment by davidhedlund** [comment] 2015-04-26 13:13
@gorhill what is the latest version of uBlock and where can I get the XPI?

**Comment by gorhill** [comment] 2015-04-26 13:14
https://github.com/chrisaljoudi/uBlock/releases

**Comment by davidhedlund** [comment] 2015-04-26 13:20
@gorhill Thank you. Can you please make sure that version get uploaded to https://addons.mozilla.org/en-US/firefox/addon/ublock/?src=search ASAP?

**Comment by davidhedlund** [comment] 2015-04-26 13:42
@gorhill What is the difference between
https://addons.mozilla.org/en-US/firefox/addon/ublock/ and 
https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ ?

**Comment by gorhill** [comment] 2015-04-26 13:56
Off the top of my head, as of writing, mostly:
- Per-site switches only in uBlock Origin
- A feature specific to Firefox not in uBlock Origin -- you can launch element picker from page inspector
- uBlock Origin still suffer from the disable remote fonts bug, fixed in uBlock
- From what I see from [@AlexVallat's work](https://github.com/chrisaljoudi/uBlock/pull/1321), uBlock will be properly supported on legacy Firefox-based browsers soon (I haven't decided if I will import this work in uBlock Origin -- I am leaning toward not importing this currently: that one version of uBlock is well supported on these older browsers seem sufficient to me)

That's what comes to mind. Otherwise all is the same, no difference in performance (I have seen this claimed in the Firefox's AMO, it's baseless).

**Comment by davidhedlund** [comment] 2015-04-26 13:59
@gorhill Can you please add this text to https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ ?

This is important.

**Comment by davidhedlund** [comment] 2015-04-26 14:42
@gorhill

From https://en.wikipedia.org/wiki/UBlock#uBlock_Origin

uBlock Origin
Version 	Release date 	Notable Changes
0.9.4.0 	April 11, 2015 	Manual editing of per-site switches and cosmetic per-site switch features added.
0.9.4.4 	April 18, 2015 	GNU.org privacy list added.
0.9.5.0 	April 24, 2015 	Color-blind mode added.


This should also be mentioned in https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

**Comment by gorhill** [comment] 2015-04-26 14:59
@flyingzebras

I see now why `https://casino-x.com/?partner=p13186p24926p73de&promo=cx_doublepimp_main_white_se_Tube8` was not blocked: the filter in EasyList works for URLs which starts with `http:`, however the `casino-x.com` URL (as you report) starts with `https:`. So this is the issue, the filter in EasyList needs to address this.

**Comment by davidhedlund** [comment] 2015-04-26 15:01
@gorhill What is the purpose of uBlock Origin?

Why not just add these features to uBlock for Firefox without enable them (the GNU filters are not enabled in uBlock Origin by the way)?

**Comment by alejandrolemus** [comment] 2015-04-26 15:29
@davidhedlund 

> What is the difference between...
> What is the purpose of uBlock Origin?

https://github.com/gorhill/uBlock, scroll down to readme.md

**Comment by davidhedlund** [comment] 2015-04-26 21:40
@alejandrolemus Thank you.

**Comment by ryanbr** [comment] 2015-04-26 23:10
Does this commit help?

https://hg.adblockplus.org/easylist/rev/caf7f8754562

**Closed as completed** 2015-05-04 20:56 UTC

**Comment by flyingzebras** [comment] 2015-05-18 20:08
@ryanbr No.
