### ISSUE TITLE
https://moltin.com is broken because of /v/ filter

### ISSUE THREAD

**Issue by extesy** [uBlock-LLC/uBlock#1035] opened 2015-03-16 21:24 UTC
https://moltin.com doesn't load many internal resources because of some /v/ filter which matches perfectly valid urls like https://moltin.com/addons/shared_addons/themes/moltin/img/favicon-3.png

By the way, is there any chance to see which filter subscription includes the particular filter?

**Comment by gorhill** [comment] 2015-03-16 21:28
I don't know what is `/v/` filter. Can you enlighten me?

In any case, most filter lists are 3rd-party to this project, and any issue with them must be addressed by their respective maintainers. I can provide workarounds only if the issue is because of filters in uBlock's own filters, or in Peter Lowe's hosts file.

**Comment by extesy** [comment] 2015-03-16 21:32
Here's the log of requests: http://i.imgur.com/jMu9LiY.png. I assume that /v/ in the left column comes from uBlock. Isn't it the case?

**Comment by gorhill** [comment] 2015-03-16 21:34
Are you saying that the filter `/v/` is blocking `https://moltin.com/addons/shared_addons/themes/moltin/img/favicon-3.png`?

If so, realize that `/v/` is a regular expression-based filter, which means "block anyth request which URL contains the letter `v`. You need to ensure the filter is not interpreted as a regular expression based filter, like so: `/v/*`.

Any filter expression wrapped within `/` will be parsed as a regular expression-based filter.

**Comment by extesy** [comment] 2015-03-16 21:34
I don't have any manual filters which contain /v/

**Comment by gorhill** [comment] 2015-03-16 21:35
Alright, let me investigate.

**Comment by gorhill** [comment] 2015-03-16 21:36
I see no `/v/` in the request log. What are your filter lists?

**Comment by extesy** [comment] 2015-03-16 21:36
Found it. This comes from fanboy-ultimate.txt list

**Comment by gorhill** [comment] 2015-03-16 21:39
I still do not see anything blocked with `/v/` when enabling Fanboy Ultimate, and opening https://moltin.com/. Only these are blocked:

```
||olark.com/nrpc/*=pollevents
||adroll.com^
||log.olark.com^
||facebook.com/tr/?
||google-analytics.com^
||optimizely.com^
```

No way that `/v/` filter would be in Fanboy Ultimate, this is clearly a nonsensical filter.

**Comment by extesy** [comment] 2015-03-16 21:42
I definitely saw it there, but after I purged caches, this /v/ filter was gone. Apparently the local cache of filter became corrupted somehow.

So I don't see this particular problem anymore with fanboy ultimate list, but maybe it's worth looking into how the cache might become corrupted?

**Comment by gorhill** [comment] 2015-03-16 21:44
What browser/version?

**Comment by extesy** [comment] 2015-03-16 21:45
Chrome Version 41.0.2272.76 (64-bit), Mac OS X 10.9.5

**Comment by gorhill** [comment] 2015-03-16 21:46
When you say you found it in Fanboy Ultimate, how did you find it specifically? You opened the cached version and searched for `/v/` in the browser?

**Comment by extesy** [comment] 2015-03-16 21:47
I clicked on the filter name in the "3rd party filters" tab in ublock options, it opened the link like ...asset-viewer.html?url=assets/thirdparties/www.fanboy.co.nz/fanboy-ultimate.txt

**Comment by gorhill** [comment] 2015-03-16 21:47
Was the filter at the end of the file?

**Comment by extesy** [comment] 2015-03-16 21:47
close to the end, yes

**Comment by gorhill** [comment] 2015-03-16 21:49
The only explanation I can see is the Fanboy server returned a truncated version of the file, wthout any error. uBlock can't know whether what it is sent is truncated or not, unless there is an error sent by the remote server.

**Comment by extesy** [comment] 2015-03-16 21:52
Well, as far as I can see, some lists include checksum at the top, like this:

```
[Adblock Plus 2.0]
! Checksum: YzpR5EU3pbA4+qXccRKpOA
! Version: 201503162141
! Title: Fanboy's Annoyance List
```

So it should be possible to confirm if downloaded list is good or not.

**Comment by gorhill** [comment] 2015-03-16 21:58
> some lists include checksum at the top

Yes, I guess uBlock should check.

**Closed as completed** 2022-09-08 21:24 UTC
