### ISSUE TITLE
The network request log should show what lists applied filters are from

### ISSUE THREAD

**Issue by anewuser** [uBlock-LLC/uBlock#877] opened 2015-02-24 17:02 UTC
When we use multiple lists, it can be impossible to tell which of them is blocking a certain request without opening every list and checking it manually.

Can you add an extra column to the network request log that identifies the list(s) that contains each applied filter?

**Comment by gorhill** [comment] 2015-02-24 17:13
Duplicate of #43.

**Closed as completed by gorhill** 2015-02-24 17:13 UTC

**Comment by anewuser** [comment] 2015-02-25 02:51
@gorhill I'm sorry for creating another duplicate. I did try to find other issues about it but failed to do so.
