### ISSUE TITLE
Element Hiding Helper

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#867] opened 2015-02-23 13:23 UTC
Sorry for my bad English, it's not my native language.
I know about uBlock's element picker, however I want to request a feature. Well, I really need Element Hiding Helper for Adblock ext. or its functionality — hotkey (Ctrl-Shift-F3) and very good advanced hiding menu. Sorry once again because of not very good statement. Thanks a lot in advance and one more «thank you» for ublock.

**Comment by gorhill** [comment] 2015-03-21 21:11
I don't know what to do with this issue. The hotkey thing is duplicate of #256.

For the rest, it's too vague. I need a **specific** issue with the element picker.

**Closed as completed** 2015-04-01 23:36 UTC
