### ISSUE TITLE
[Firefox] No element hiding upon start

### ISSUE THREAD

**Issue by DotTheI** [uBlock-LLC/uBlock#991] opened 2015-03-11 17:56 UTC
I am using FF 36.0.1 for OS X 10.10 with uBlock 0.9. uBlock is not hiding selected elements when a page where the elements are found is loaded upon FF start. The uBlock icon is gray then. Once the page is refreshed, elements are hidden properly and the icon is red.

**Comment by gorhill** [comment] 2015-03-11 18:04
Provide [steps to reproduce, with specific URL, filter lists, etc.](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include)

**Comment by DotTheI** [comment] 2015-03-11 18:44
I (re)start browser with http://rutracker.org/forum/index.php already opened. The filters I am using are:

! 11/03/2015 21:17:33 http://rutracker.org/forum/viewtopic.php?t=4610627
||195.82.146.52/logo/logo.gif

! 11/03/2015 21:17:46 http://rutracker.org/forum/viewtopic.php?t=4610627
rutracker.org###logo > .w100 > tbody > tr > .tCenter.w100

! 11/03/2015 21:17:55 http://rutracker.org/forum/viewtopic.php?t=4610627
rutracker.org###logo

! 11/03/2015 22:38:39 http://rutracker.org/forum/index.php
||ad.ddestiny.ru/bb/rutracker_left?rnd=370158360

! 11/03/2015 22:39:32 http://rutracker.org/forum/index.php
rutracker.org###ddest-bn-1

The top of the page should look like this:
![2015-03-11 21 42 21](https://cloud.githubusercontent.com/assets/10737439/6604137/94bdc2aa-c837-11e4-9bfc-ad0644fb3ada.png)
However, upon (re)start it looks like this:
![2015-03-11 21 43 40](https://cloud.githubusercontent.com/assets/10737439/6604166/bb62c518-c837-11e4-8063-0508e7f8e6c5.png)

**Comment by gorhill** [comment] 2015-03-11 18:53
Selected filter lists please.

**Comment by gorhill** [comment] 2015-03-11 18:55
I could not reproduce with the information you gave me so far.

Of interest... What other extensions you have installed?

**Comment by DotTheI** [comment] 2015-03-11 18:57
Not sure what the selected filters list is. This?
![2015-03-11 21 55 24](https://cloud.githubusercontent.com/assets/10737439/6604470/9fd31d00-c839-11e4-9848-072c386a6060.png)

**Comment by DotTheI** [comment] 2015-03-11 18:58
The other add-on being used are:
![2015-03-11 21 55 55](https://cloud.githubusercontent.com/assets/10737439/6604482/af021f42-c839-11e4-9860-ec4eedff2c10.png)

**Comment by gorhill** [comment] 2015-03-11 19:24
Ok, given the large amount of other add-ons, it's unlikely uBlock is guaranteed to be fully loaded before the web page loads.

The solution in such case is to implement for Firefox what is implemented in Chromium: to inject the content scripts on already opened web pages once uBlock finishes loading.

**Comment by DotTheI** [comment] 2015-03-11 19:27
Please advise, how does one injects the content scripts?

**Comment by gorhill** [comment] 2015-03-11 19:29
It's for the extension to do this, not you.

**Comment by DotTheI** [comment] 2015-03-11 19:32
I see. Does that mean there's nothing I can do to fix the issue? If so, thank you for your help! And thank you very much for development of uBlock!

**Comment by gorhill** [comment] 2015-03-11 19:34
> Does that mean there's nothing I can do to fix the issue?

Not that I am aware. If there is a way to ensure uBlock is loaded before all other extensions that would probably fix your issue, but I have no idea whether this is possible.

**Comment by elyrly** [comment] 2015-03-11 23:27
@DotTheI
I tried reproducing the issue with the  parameters you provided and was not able to show the logo and left-handed flash. Disable the other extensions and check again. Let us know the results.

**Comment by gorhill** [comment] 2015-03-12 14:43
@Deathamns Is it possible to inject content scripts on the active tab when [`vAPI.onLoadAllCompleted`](https://github.com/gorhill/uBlock/blob/master/platform/firefox/vapi-background.js#L1850) is called at launch time?

**Comment by Deathamns** [comment] 2015-03-12 14:47
Yes, I guess.

**Comment by gorhill** [comment] 2015-03-12 18:02
Fixed with 4ad98583579c8b187e7008e70d1ac30fd20404c8.

I tested by enabling the extension after pages are loaded, and I confirm it worked.

**Closed as completed by gorhill** 2015-03-12 18:02 UTC

**Comment by Deathamns** [comment] 2015-03-12 18:22
However it doesn't (I didn't know a way) detect if the content scripts are already loaded, so it will load it again. Nor will it destroy them if the extension is disabled.

**Comment by gorhill** [comment] 2015-03-12 18:34
[This code](https://github.com/gorhill/uBlock/blob/master/platform/chromium/vapi-client.js#L39) works on Chromium. Something like this would not work as well on Firefox?

**Comment by Deathamns** [comment] 2015-03-12 18:39
I create sandboxes in Firefox, which cannot be reached just like that. Chrome loads scripts into the same extension context. I'll try something else.

**Comment by DotTheI** [comment] 2015-03-13 17:44
I haven't tested yet, however, I just noticed that the rutracker.org logo 195.82.146.52/logo/logo.gif is blacklisted. Please do not blacklist it! It's not an ad, it's just my own preference not to have it shown.

PS I am having difficulties understanding how to tell uBlock not to block certain elements?

**Comment by gorhill** [comment] 2015-03-13 17:52
> Please do not blacklist it!

Nothing to do with uBlock, it's 3rd-party lists blocking it.

**Comment by gorhill** [comment] 2015-03-13 17:58
Actually, it's BitBlock list causing the logo to disappear. There must be a element hiding rule in there somewhere.

**Comment by gorhill** [comment] 2015-03-13 18:00
Found the culprit:

    assets/thirdparties/easylist-downloads.adblockplus.org/bitblock.txt:12307:alltorrents.net,file-tracker.net,free-torrents.org,pornolab.cc,pornolab.net,rus-torrents.ru,rutracker.org,rutracker.ru,underverse.su###logo

**Comment by DotTheI** [comment] 2015-03-13 18:06
Thank you gorhill! Have disabled the BitBlock list. I still would like to know how to disable certain filters. Is it possible?

**Comment by gorhill** [comment] 2015-03-13 18:09
Create an exception filter: [Writing Adblock Plus filters: Defining exception rules](https://adblockplus.org/en/filters#whitelist).

**Comment by DotTheI** [comment] 2015-03-13 18:28
Please advise, how do I create an exception filter? Do I have to edit .txt files?

**Comment by gorhill** [comment] 2015-03-13 18:33
![d](https://cloud.githubusercontent.com/assets/585534/6644869/de98f884-c98d-11e4-9631-650f688c5d65.png)
