### ISSUE TITLE
[Firefox] Autoupdate from https://github.com/gorhill/uBlock/releases xpi versions

### ISSUE THREAD

**Issue by onesolo** [uBlock-LLC/uBlock#1147] opened 2015-04-01 08:58 UTC
Please, make the versions that you put in https://github.com/gorhill/uBlock/releases , be the more stable versions or the dev versions, to be self updated (via Firefox addon settings) if they are installed via https://github.com/gorhill/uBlock/releases

For example, I have an addon, Downthemall (on of the most used addons from Firefox), that have a nightly version of the addon that is only available from their own website, that if I have installed that version, from onward I get an update every day (as long as it's released).

I mainly ask this, because the two versions that are available from Firefox addon page, https://addons.mozilla.org/en-US/firefox/addon/ublock/?src=userprofile , are all outdated !!!

Please, think about this... it is painfully to have to go everytime to github to have the latest version...

**Comment by lewisje** [comment] 2015-04-01 10:25
I'm thinking that they privileged the AMO copy early on just to encourage users to get updates on AMO once the extension was finally approved, and then they'll start having the GitHub builds updating from GitHub once the AMO ball is rolling, or they might have just the dev builds update from GitHub while keeping the stable builds checking AMO, even if they're installed from GitHub.

By the way, the AMO builds won't be so outdated once the project has passed "preliminary review" status: https://github.com/gorhill/uBlock#firefox

**Comment by gorhill** [comment] 2015-04-01 12:11
> from their own website

There is no web site for uBlock. As said elsewhere, I don't want donations, I don't want expenses either.

Duplicate of #925.

**Closed as completed by gorhill** 2015-04-01 12:11 UTC
