### ISSUE TITLE
Add a hotkey for element picker mode

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#794] opened 2015-02-14 23:11 UTC
Using the element picker can be currently quite slow and cumbersome because as per [the wiki](https://github.com/gorhill/uBlock/wiki/Element-picker) you need to "open the extension's popup menu, and click the small "eye-dropper" icon" every time you want to add a new custom filter rule.

Adblock Edge/Plus have [Element Hider Helper](https://addons.mozilla.org/en-US/firefox/addon/elemhidehelper/) that have a nice hotkey by default.

**Comment by gorhill** [comment] 2015-02-15 05:29
You can also right-click and click "Block element".

**Comment by Havokdan** [comment] 2015-02-15 08:53
I agree with feature request.

**Comment by mzso** [comment] 2015-02-17 16:15
This would certainly make life easier.

**Comment by gorhill** [comment] 2015-02-18 18:05
Duplicate of #256.

**Closed as completed by gorhill** 2015-02-18 18:05 UTC

**Comment by robsonreisunb** [comment] 2017-06-19 18:11
I need this hotkey
