### ISSUE TITLE
[Firefox] Blocked iframe left empty space

### ISSUE THREAD

**Issue by kasper93** [uBlock-LLC/uBlock#1116] opened 2015-03-28 15:41 UTC
While trying to find site for the other issue. I've found that on rutracker.org blocking iframes result in leftover empty space (menu on the left hand side). Works fine on Chrome.

rules:

```
||ad.ddestiny.ru
||195.82.146.52/iframe-MG-200-1.html
||195.82.146.52/iframe-begun-200x300-1.html
```

EDIT:

Also it is imposible to pick .sfw with picker, because it will execute click event of flash instead of uBlcok's.

**Comment by gorhill** [comment] 2015-03-28 16:10
> on rutracker.org blocking iframes result in leftover empty space

What's wrong with `rutracker.org`?

![a](https://cloud.githubusercontent.com/assets/585534/6881749/4c8bbac8-d543-11e4-8a31-690bf335d13b.png)

> imposible to pick .sfw with picker

URL please.

**Comment by kasper93** [comment] 2015-03-28 16:19
> What's wrong with rutracker.org?

The same rules with Chrome
![chrome](https://cloud.githubusercontent.com/assets/1126053/6881767/ebbc8a1c-d56d-11e4-88ec-01af340b92be.png)

> URL please.

I can reproduce it on every site. See image, you can't select that on Firefox. (you need to disable rules to reproduce ofc)
![rut](https://cloud.githubusercontent.com/assets/1126053/6881782/9ff8d166-d56e-11e4-9bfa-a2cecc501389.png)

**Comment by gorhill** [comment] 2015-03-28 16:44
> you can't select that on Firefox

It's a Firefox issue, there is nothing uBlock can do. Using "Ask to activate" in Firefox work around the issue.

**Comment by gorhill** [comment] 2015-03-28 16:52
> blocking iframes result in leftover empty space

Pretty sure this is a duplicate of #618.

**Closed as completed by gorhill** 2015-03-28 16:52 UTC
